// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-ldBznTsE0VTcjjAp0nLTJYw8mzwm4zc',
    appId: '1:898952786530:web:7466825ba40fb54208d73b',
    messagingSenderId: '898952786530',
    projectId: 'mokars',
    authDomain: 'mokars.firebaseapp.com',
    storageBucket: 'mokars.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNe2zqDqiRNUjkHflCrNEfJL2nNbLaxQ',
    appId: '1:15232945274:android:58b939864161b88fa2ffc3',
    messagingSenderId: '15232945274',
    projectId: 'ruangku-f6c48',
    storageBucket: 'ruangku-f6c48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTp7tDLlRbTfeO0JKwyztxv8uLPO4B0Y0',
    appId: '1:15232945274:ios:521ed070cbc129a9a2ffc3',
    messagingSenderId: '15232945274',
    projectId: 'ruangku-f6c48',
    storageBucket: 'ruangku-f6c48.firebasestorage.app',
    iosBundleId: 'id.co.androdevjik.mokars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOuUzmjbyTsUn5oB24CwLhwZTND80G9f0',
    appId: '1:898952786530:ios:b8893e38f408784308d73b',
    messagingSenderId: '898952786530',
    projectId: 'mokars',
    storageBucket: 'mokars.firebasestorage.app',
    iosBundleId: 'id.co.androdevjik.mokars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-ldBznTsE0VTcjjAp0nLTJYw8mzwm4zc',
    appId: '1:898952786530:web:3fc8ae383a0657be08d73b',
    messagingSenderId: '898952786530',
    projectId: 'mokars',
    authDomain: 'mokars.firebaseapp.com',
    storageBucket: 'mokars.firebasestorage.app',
  );
}